---
version: "2.1"
services:
  netbootxyz:
    image: ghcr.io/netbootxyz/netbootxyz
    container_name: netbootxyz
    volumes:
      - /opt/netbootxyz/config:/config
      - /opt/netbootxyz/assets:/assets
      - /vagrant/netbootxyz/assets:/vagrant/netbootxyz/assets
      - /vagrant/netbootxyz/config:/vagrant/netbootxyz/config
    ports:
      - 3001:3000
      - 69:69/udp
      - 80:80
    restart: unless-stopped