---
version: "2.1"
services:
  netbootxyz:
    image: ghcr.io/netbootxyz/netbootxyz
    container_name: netbootxyz
#    volumes:
#      - /path/to/config:/config # optional
#      - /path/to/assets:/assets # optional
    ports:
      - 3001:3000
      - 69:69/udp
      - 8080:80 #optional
    restart: unless-stopped